#!/bin/bash

ENV_NAME=$1
VERSION=$2

. $(dirname $0)/get-component-name

SLUG_LOCATION=http://192.168.0.241/$COMPONENT_NAME-$VERSION

if [ -z "$ENV_NAME" ] || [ -z "$SLUG_LOCATION" ]
then
  echo "Usage: deploy ENV_NAME VERSION" >&2
  exit 1
fi

NAME=$ENV_NAME-$COMPONENT_NAME

curl -f 192.168.0.240:8000/app/$NAME 2>/dev/null

if [ "$?" != "0" ]
then
  curl -X POST -H 'Content-type: application/json' 192.168.0.240:8000/app/ -d "{ \"name\": \"$NAME\" }"
  curl -X PATCH -H 'Content-type: application/json' 192.168.0.240:8000/app/$NAME -d "{ \"docker_image\": \"flynn/slugrunner\", \"command\": \"start web\", \"urls\": \"$NAME.domain.com\" }" 
fi

#Now deploy

curl -X PATCH -H 'Content-type: application/json' 192.168.0.240:8000/app/$NAME -d "{ \"environment\": { \"SLUG_URL\": \"$SLUG_LOCATION\" } }"


